FROM golang:1.24-alpine AS build-stage

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY *.go /app
COPY api/ api/
COPY cache/ cache/
COPY weather/ weather/

RUN CGO_ENABLED=0 GOOS=linux go build -o /weather-api

# Deploy the application binary into a lean image
FROM gcr.io/distroless/base-debian11 AS build-release-stage

WORKDIR /

COPY --from=build-stage /weather-api /weather-api

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT [ "/weather-api" ]