services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.multistage
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    env_file: 
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"